spring:
  datasource:
#    url: "jdbc:mysql://localhost:3306/informatics_db?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    url: "mysql://b1cf57e467c21a:3dc9d480@us-cdbr-east-02.cleardb.com/heroku_93fcc7c7861a86b?reconnect=true&createDatabaseIfNotExist=true"
#    username: "root"
    username: "b1cf57e467c21a"
#    password: "root"
    password: "3dc9d480"
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  thymeleaf:
    cache: false
server:
  port: ${PORT:8080}
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
informatics:
  cleanup-schedule-time: "0 0,30 * ? * *"
  update-cache-schedule-time: "0 0,6,12,18,24,30,36,42,48,54 * ? * *"
#  "0 */30 * ? * *"

# Cloudinary properties
cloudinary:
  cloud-name: dthoksfe5
  api-key: 644331637917722
  api-secret: pC9S2PY0SKIn0gNCM-NGaftwwBE