spring:
  datasource:
    url: "jdbc:mysql://b00adf0878c10b:0d1ba06d@us-cdbr-east-02.cleardb.com:3306/heroku_bedffa3863ce004?reconnect=true&createDatabaseIfNotExist=true"
    username: "b00adf0878c10b"
    password: "0d1ba06d"
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  thymeleaf:
    cache: false
server:
  port: 8080
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
informatics:
  cleanup-schedule-time: "0 0,30 * ? * *"
  update-cache-schedule-time: "0 0,6,12,18,24,30,36,42,48,54 * ? * *"
#  "0 */30 * ? * *"

# Cloudinary properties
cloudinary:
  cloud-name: dthoksfe5
  api-key: 644331637917722
  api-secret: pC9S2PY0SKIn0gNCM-NGaftwwBE